#	$OpenBSD$

PROG=test_sshbuf
SRCS=tests.c test_sshbuf.c test_sshbuf_getput_basic.c test_sshbuf_getput_crypto.c
SRCS+=test_sshbuf_misc.c test_sshbuf_fuzz.c test_sshbuf_getput_fuzz.c

.include <bsd.regress.mk>

